### ISSUE TITLE
Opam release with recent changes

### ISSUE THREAD

**Issue by Simn** [NielsMommen/ppx_parser#7]
Over at https://github.com/HaxeFoundation/haxe/pull/11860 we're just about ready to change our parser implementation to use `ppx_parser`. Could we get an opam release so that it's easier to setup? Ideally with #6 merged as well.

Thank you!

**Comment by NielsMommen** [comment]
I'll push a new release to opam soon.

**Comment by NielsMommen** [comment]
New release is merged in opam-repository (https://github.com/ocaml/opam-repository/pull/27068)
